name: Build 6502 Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y cc65 make nodejs python3

      - name: Build exomizer
        run: |
          apt-get update
          apt-get install -y build-essential git
          git clone https://bitbucket.org/magli143/exomizer.git
          cd exomizer
          make
          cp exomizer /usr/local/bin/

      - name: Build
        run: |
          cd ./src
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/**/*.prg
            build/**/*.bin
            build/**/*.d64
