name: Build 6502 Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/actions/runner:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install cc65
        run: |
          apt-get update
          apt-get install -y cc65 make

      - name: Build
        run: |
          cd ./src
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/**/*.prg
            build/**/*.bin
            build/**/*.d64
